name: Deploy to digital ocean cluster

on:
  workflow_dispatch
  
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-hub/kubectl@master
      env: 
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: get pods
